export const BASE_LEVEL = {
  newLevel: {
    arrows: [
      {
        arrow: {
          index: 0,
          orientation: "BOTTOM",
          coordinate: { x: 180, y: 265 },
          state: "IDLE",
          rotation: 180,
        },
        indexLines: [0, 1, 2],
        targetPositions: [
          { coordinate: { x: 180, y: 302 }, orientation: "RIGHT" },
          { coordinate: { x: 255, y: 302 }, orientation: "TOP" },
          { coordinate: { x: 255, y: 265 }, orientation: "LEFT" },
        ],
        indexArrival: 0,
      },
      {
        arrow: {
          index: 1,
          orientation: "LEFT",
          coordinate: { x: 143, y: 340 },
          state: "IDLE",
          rotation: 270,
        },
        indexLines: [3, 4],
        targetPositions: [
          { coordinate: { x: 105, y: 340 }, orientation: "TOP" },
          { coordinate: { x: 105, y: 265 }, orientation: "LEFT" },
        ],
        indexArrival: 1,
      },
      {
        arrow: {
          index: 2,
          orientation: "RIGHT",
          coordinate: { x: 218, y: 340 },
          state: "IDLE",
          rotation: 90,
        },
        indexLines: [5, 6],
        targetPositions: [
          { coordinate: { x: 255, y: 340 }, orientation: "BOTTOM" },
          { coordinate: { x: 255, y: 415 }, orientation: "LEFT" },
        ],
        indexArrival: 2,
      },
      {
        arrow: {
          index: 3,
          orientation: "TOP",
          coordinate: { x: 180, y: 415 },
          state: "IDLE",
          rotation: 0,
        },
        indexLines: [7, 8, 9],
        targetPositions: [
          { coordinate: { x: 180, y: 377 }, orientation: "TOP" },
          { coordinate: { x: 105, y: 377 }, orientation: "BOTTOM" },
          { coordinate: { x: 105, y: 415 }, orientation: "LEFT" },
        ],
        indexArrival: 3,
      },
    ],
    lines: [
      {
        index: 0,
        coordinate: { x: 204, y: 291 },
        height: 39,
        width: 4,
        transform: { scale: "scaleY", origin: "bottom" },
        value: 1,
        finish: "NEXT",
      },
      {
        index: 1,
        coordinate: { x: 204, y: 327 },
        height: 4,
        width: 79,
        transform: { scale: "scaleX", origin: "right" },
        value: 1,
        finish: "NEXT",
      },
      {
        index: 2,
        coordinate: { x: 279, y: 291 },
        height: 39,
        width: 4,
        transform: { scale: "scaleY", origin: "top" },
        value: 1,
        finish: "ARRIVAL",
      },
      {
        index: 3,
        coordinate: { x: 129, y: 364 },
        height: 4,
        width: 41,
        transform: { scale: "scaleX", origin: "left" },
        value: 1,
        finish: "NEXT",
      },
      {
        index: 4,
        coordinate: { x: 129, y: 290 },
        height: 78,
        width: 4,
        transform: { scale: "scaleY", origin: "top" },
        value: 1,
        finish: "ARRIVAL",
      },
      {
        index: 5,
        coordinate: { x: 242, y: 364 },
        height: 4,
        width: 41,
        transform: { scale: "scaleX", origin: "right" },
        value: 1,
        finish: "NEXT",
      },
      {
        index: 6,
        coordinate: { x: 279, y: 364 },
        height: 79,
        width: 4,
        transform: { scale: "scaleY", origin: "bottom" },
        value: 1,
        finish: "ARRIVAL",
      },
      {
        index: 7,
        coordinate: { x: 204, y: 401 },
        height: 39,
        width: 4,
        transform: { scale: "scaleY", origin: "top" },
        value: 1,
        finish: "NEXT",
      },
      {
        index: 8,
        coordinate: { x: 129, y: 401 },
        height: 4,
        width: 79,
        transform: { scale: "scaleX", origin: "left" },
        value: 1,
        finish: "NEXT",
      },
      {
        index: 9,
        coordinate: { x: 129, y: 401 },
        height: 39,
        width: 4,
        transform: { scale: "scaleY", origin: "bottom" },
        value: 1,
        finish: "ARRIVAL",
      },
    ],
    stoppers: [],
    arrivals: [
      { index: 0, coordinate: { x: 255, y: 265 } },
      { index: 1, coordinate: { x: 105, y: 265 } },
      { index: 2, coordinate: { x: 255, y: 415 } },
      { index: 3, coordinate: { x: 105, y: 415 } },
    ],
  },
  arrows: [
    {
      index: 0,
      orientation: "BOTTOM",
      coordinate: { x: 180, y: 265 },
      state: "IDLE",
      rotation: 180,
    },
    {
      index: 1,
      orientation: "LEFT",
      coordinate: { x: 143, y: 340 },
      state: "IDLE",
      rotation: 270,
    },
    {
      index: 2,
      orientation: "RIGHT",
      coordinate: { x: 218, y: 340 },
      state: "IDLE",
      rotation: 90,
    },
    {
      index: 3,
      orientation: "TOP",
      coordinate: { x: 180, y: 415 },
      state: "IDLE",
      rotation: 0,
    },
  ],
  lines: [
    {
      index: 0,
      coordinate: { x: 204, y: 291 },
      height: 39,
      width: 4,
      transform: { scale: "scaleY", origin: "bottom" },
      value: 1,
      finish: "NEXT",
    },
    {
      index: 1,
      coordinate: { x: 204, y: 327 },
      height: 4,
      width: 79,
      transform: { scale: "scaleX", origin: "right" },
      value: 1,
      finish: "NEXT",
    },
    {
      index: 2,
      coordinate: { x: 279, y: 291 },
      height: 39,
      width: 4,
      transform: { scale: "scaleY", origin: "top" },
      value: 1,
      finish: "ARRIVAL",
    },
    {
      index: 3,
      coordinate: { x: 129, y: 364 },
      height: 4,
      width: 41,
      transform: { scale: "scaleX", origin: "left" },
      value: 1,
      finish: "NEXT",
    },
    {
      index: 4,
      coordinate: { x: 129, y: 290 },
      height: 78,
      width: 4,
      transform: { scale: "scaleY", origin: "top" },
      value: 1,
      finish: "ARRIVAL",
    },
    {
      index: 5,
      coordinate: { x: 242, y: 364 },
      height: 4,
      width: 41,
      transform: { scale: "scaleX", origin: "right" },
      value: 1,
      finish: "NEXT",
    },
    {
      index: 6,
      coordinate: { x: 279, y: 364 },
      height: 79,
      width: 4,
      transform: { scale: "scaleY", origin: "bottom" },
      value: 1,
      finish: "ARRIVAL",
    },
    {
      index: 7,
      coordinate: { x: 204, y: 401 },
      height: 39,
      width: 4,
      transform: { scale: "scaleY", origin: "top" },
      value: 1,
      finish: "NEXT",
    },
    {
      index: 8,
      coordinate: { x: 129, y: 401 },
      height: 4,
      width: 79,
      transform: { scale: "scaleX", origin: "left" },
      value: 1,
      finish: "NEXT",
    },
    {
      index: 9,
      coordinate: { x: 129, y: 401 },
      height: 39,
      width: 4,
      transform: { scale: "scaleY", origin: "bottom" },
      value: 1,
      finish: "ARRIVAL",
    },
  ],
  arrivals: [
    { index: 0, coordinate: { x: 255, y: 265 } },
    { index: 1, coordinate: { x: 105, y: 265 } },
    { index: 2, coordinate: { x: 255, y: 415 } },
    { index: 3, coordinate: { x: 105, y: 415 } },
  ],
  stoppers: [],
  arrowsLinks: {
    "0": { lines: [0, 1, 2], arrival: -1, positions: [] },
    "1": { lines: [3, 4], arrival: -1, positions: [] },
    "2": { lines: [5, 6], arrival: -1, positions: [] },
    "3": { lines: [7, 8, 9], arrival: -1, positions: [] },
  },
  arrowsGhost: [
    {
      index: 0,
      orientation: "RIGHT",
      coordinate: { x: 180, y: 302 },
      indexArrow: 0,
    },
    {
      index: 1,
      orientation: "TOP",
      coordinate: { x: 255, y: 302 },
      indexArrow: 0,
    },
    {
      index: 2,
      orientation: "TOP",
      coordinate: { x: 105, y: 340 },
      indexArrow: 1,
    },
    {
      index: 3,
      orientation: "BOTTOM",
      coordinate: { x: 255, y: 340 },
      indexArrow: 2,
    },
    {
      index: 4,
      orientation: "TOP",
      coordinate: { x: 180, y: 377 },
      indexArrow: 3,
    },
    {
      index: 5,
      orientation: "BOTTOM",
      coordinate: { x: 105, y: 377 },
      indexArrow: 3,
    },
  ],
};
